services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"   # Untuk internal dashboard
      - "9094:9094"   # KHUSUS untuk producer di laptop (localhost)
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@127.0.0.1:9093'
      
      # Mendefinisikan 3 jalur: Internal, External (Outside), dan Controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT'
      
      # Jalur OUTSIDE mendengarkan di port 9094
      KAFKA_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9093,OUTSIDE://:9094'
      
      # PENTING: Jika diakses dari localhost, arahkan ke 9094. Jika dari container, ke 9092.
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,OUTSIDE://localhost:9094'
      
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'